//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_product()
        {
            this.tbl_pro_img = new HashSet<tbl_pro_img>();
        }
    
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_image { get; set; }
        public Nullable<int> pro_fk_address_city { get; set; }
        public string pro_address_street { get; set; }
        public Nullable<int> pro_address_building_num { get; set; }
        public Nullable<int> pro_address_floor { get; set; }
        public int pro_price { get; set; }
        public string pro_description { get; set; }
        public string pro_type { get; set; }
        public Nullable<int> pro_room_size { get; set; }
        public Nullable<int> pro_room_num { get; set; }
        public Nullable<int> pro_bathroom_num { get; set; }
        public Nullable<int> pro_roommates { get; set; }
        public bool pro_TV { get; set; }
        public bool pro_internet { get; set; }
        public bool pro_ac { get; set; }
        public bool pro_parking { get; set; }
        public string pro_heating { get; set; }
        public bool pro_elevator { get; set; }
        public bool pro_balcony { get; set; }
        public bool pro_handicapped { get; set; }
        public bool pro_smoking { get; set; }
        public bool pro_pet { get; set; }
        public int pro_fk_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pro_img> tbl_pro_img { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_wojewodztwa_miasta tbl_wojewodztwa_miasta { get; set; }
    }
}
