//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pro_img
    {
        public int pro_img_id { get; set; }
        public int pro_img_fk_pro_id { get; set; }
        public string pro_img_path { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
    }
}
